#!/usr/bin/env node
/* ============================================================================
   make-blocks — STAND-IN geometry for the Outside Work section.

   The delivered art (master_block.svg, block_1..4.svg) has not landed yet.
   Rather than build the traversal against nothing, this writes blocks that
   satisfy every condition in spec section 3 — tight viewBox, one variant per
   file, identical export scale, faces as separate paths carrying id="top" /
   "left" / "right", flat fills bound to CSS variables, no rasters, no baked
   shadows — so the engine can be built, tuned and reviewed now, and the real
   files simply overwrite these by name.

   Every file it writes carries data-placeholder="1". The loader warns on it,
   so a stand-in can never quietly ship as if it were the delivered art.

   The angle is a parameter because the angle is UNVERIFIED. Spec section 2
   says to measure the real master block before anything else; until that file
   exists there is nothing to measure, so these are drawn at the isometric
   default the rest of the site already uses. When the art arrives:

     node tools/measure-iso.mjs public/img/master_block.svg

   and if it comes back dimetric, regenerate with --ratio 0.5 and change the
   one ISO constant in assets/js/outside.js. Nothing else moves.

   Usage:
     node tools/make-blocks.mjs [--ratio 0.5039] [--out public/img]
   ========================================================================== */

import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const argv = process.argv.slice(2);
const arg = (k, d) => {
  const i = argv.indexOf(k);
  return i === -1 ? d : argv[i + 1];
};

/* The rise/run of the front-right edge. 0.5833 is the site's own depth vector
   (+120,-70) resolved as 70/120 — the axis the hero's blocks are already drawn
   on, and the spec's "~0.583" row. It is the defensible guess, not a
   measurement: mind that this is the EDGE RATIO, not the AY component of the
   unit axis vector, which for that same projection is 0.5039. Confusing the
   two draws a dimetric block and calls it isometric. */
const RATIO = Number(arg('--ratio', 0.5833));
const OUT   = arg('--out', 'public/img');

/* One variant per file, all at the same units-per-pixel. The master is the
   only one that carries a mascot, so it is the only one that needs a ridge. */
const VARIANTS = [
  { key: 'master', file: 'master_block.svg', w: 420, h: 150, ridge: true },
  { key: 'amb_1',  file: 'block_1.svg',      w: 300, h: 118 },
  { key: 'amb_2',  file: 'block_2.svg',      w: 220, h:  86 },
  { key: 'amb_3',  file: 'block_3.svg',      w: 150, h:  58 },
  { key: 'amb_4',  file: 'block_4.svg',      w: 260, h:  30 }
];

const r2 = n => Math.round(n * 100) / 100;

function block({ file, w, h, ridge }) {
  /* The top face, as a rhombus in screen space. Four vertices, named for where
     they sit rather than for their order, because every anchor below is
     expressed against them.

        back        (w/2, 0)
        left        (0,   r*w/2)
        right       (w,   r*w/2)
        front       (w/2, r*w)      <- nearest, lowest corner of the TOP face

     The edge front->right is the one measure-iso.mjs reads back, and by
     construction its rise/run is exactly RATIO. */
  const ty = RATIO * w / 2;      // half-depth of the top face
  const fy = RATIO * w;          // the front vertex
  const H  = fy + h;             // total height, tight to the geometry

  const top   = `M${r2(w/2)} 0L${r2(w)} ${r2(ty)}L${r2(w/2)} ${r2(fy)}L0 ${r2(ty)}Z`;
  const left  = `M0 ${r2(ty)}L${r2(w/2)} ${r2(fy)}L${r2(w/2)} ${r2(H)}L0 ${r2(ty + h)}Z`;
  const right = `M${r2(w/2)} ${r2(fy)}L${r2(w)} ${r2(ty)}L${r2(w)} ${r2(ty + h)}L${r2(w/2)} ${r2(H)}Z`;

  const svg =
`<svg xmlns="http://www.w3.org/2000/svg" width="${r2(w)}" height="${r2(H)}"
     viewBox="0 0 ${r2(w)} ${r2(H)}" fill="none" data-placeholder="1">
<!-- STAND-IN. Generated by tools/make-blocks.mjs at ratio ${RATIO}.
     Replace with the delivered art of the same name. See docs/outside-work.md. -->
<path id="top"   fill="var(--blk-top,   #5CC13C)" d="${top}"/>
<path id="left"  fill="var(--blk-left,  #43A62F)" d="${left}"/>
<path id="right" fill="var(--blk-right, #2F7D22)" d="${right}"/>
</svg>
`;

  /* Anchors as fractions of the file's own box, so they survive any scaling.

     origin — the front-bottom vertex. Everything in the world positions here.

     ridge  — where the mascot's feet go. Not the front lip: a figure standing
     on the very edge reads as about to fall off it, the same reason the
     mascot on the plinth over in Things That Move stands 40% back rather than
     at 47%. So it is the midpoint between the top face's centre and its front
     vertex — a step back onto the face. */
  const anchors = { origin: { x: 0.5, y: 1 } };
  if (ridge) anchors.ridge = { x: 0.5, y: r2(((ty + fy) / 2) / H * 1000) / 1000 };
  return { svg, anchors, w: r2(w), h: r2(H) };
}

mkdirSync(OUT, { recursive: true });

const manifest = {};
for (const v of VARIANTS) {
  const b = block(v);
  writeFileSync(join(OUT, v.file), b.svg);
  manifest[v.key] = { file: v.file, ...b.anchors, nw: b.w, nh: b.h };
  console.log(`wrote ${join(OUT, v.file)}  ${b.w}x${b.h}`);
}

console.log('\n--- BLOCKS manifest (paste into assets/js/outside.js) ---\n');
for (const [k, v] of Object.entries(manifest)) {
  const ridge = v.ridge ? `, ridge:{x:${v.ridge.x},y:${v.ridge.y}}` : '';
  console.log(`  ${k.padEnd(7)}: { src:'${v.file}', nw:${v.nw}, nh:${v.nh}, origin:{x:${v.origin.x},y:${v.origin.y}}${ridge} },`);
}
console.log();
